# Generated by Django 4.2.5 on 2023-09-29 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_alter_mensage_updated_alter_room_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='Participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
